Repository caos/orbos, pull requests merged in 2020-05, with the labels that each got.

#95 chore: codecov config and badge, dependabot config
  .codecov/codecov.yml
  .dependabot/config.yml
  README.md
Labels: documentation

#96 docs(security): policy
  SECURITY.md
Labels: documentation

#125 chore(dependabot): set cycle to weekly
  .dependabot/config.yml
Labels: dependencies, enhancement

#135 docs(ORBOS): explained
  README.md
  docs/explained.md
  docs/img/orbos-explained-flowchart.svg
  docs/orbiter/orbiter.md
Labels: documentation

#133 fix(memory): memoryoptimization through minimising garbage-collection of heap allocated space
  Dockerfile
  cmd/orbctl/takeoff.go
  internal/executables/builder_test.go
  internal/executables/runtime.go
  internal/operator/common/yaml.go
  internal/operator/nodeagent/dep/cri/ensure.go
  internal/operator/nodeagent/dep/hostname/dep.go
  internal/operator/nodeagent/dep/iteratefile_test.go
  internal/operator/nodeagent/dep/k8s/common.go
  internal/operator/nodeagent/dep/k8s/kubelet/dep.go
  internal/operator/nodeagent/dep/keepalived/dep.go
  internal/operator/nodeagent/dep/nginx/dep.go
  internal/operator/nodeagent/dep/package-manager-addrepo.go
  internal/operator/nodeagent/dep/package-manager-init.go
  internal/operator/nodeagent/dep/package-manager-install.go
  internal/operator/nodeagent/dep/selinux/selinux.go
  internal/operator/nodeagent/dep/sshd/dep.go
  internal/operator/nodeagent/dep/swap/dep.go
  internal/operator/nodeagent/dep/system.go
  internal/operator/nodeagent/dep/systemd.go
  internal/operator/nodeagent/firewall/centOS.go
  internal/operator/orbiter/adapt.go
  internal/operator/orbiter/destroy.go
  internal/operator/orbiter/kinds/clusters/clusters.go
  internal/operator/orbiter/kinds/clusters/kubernetes/adapt.go
  internal/operator/orbiter/kinds/clusters/kubernetes/join.go
  internal/operator/orbiter/kinds/loadbalancers/dynamic/adapt.go
  internal/operator/orbiter/kinds/loadbalancers/loadbalancers.go
  internal/operator/orbiter/kinds/orb/adapt.go
  internal/operator/orbiter/kinds/providers/providers.go
  internal/operator/orbiter/kinds/providers/static/adapt.go
  internal/operator/orbiter/kinds/providers/static/computesservice.go
  internal/operator/orbiter/kinds/providers/static/ensure.go
  internal/operator/orbiter/kinds/providers/static/ssh/machine.go
  internal/operator/orbiter/takeoff.go
  internal/secret/secret.go
  internal/ssh/ssh.go
  internal/tree/tree.go
Labels: enhancement

#134 fix(orbiter): custom names for the kubernetes cluster in kubeconfig
  examples/k8s/static/virt-install/kickstart.cfg
  examples/k8s/static/virt-install/machine.sh
  examples/k8s/static/virt-install/orbiter.yml
  examples/k8s/static/virtualbox/downloadImage.sh
  examples/k8s/static/virtualbox/exampleClusterPostSteps.sh
  examples/k8s/static/virtualbox/exampleClusterStart.sh
  examples/k8s/static/virtualbox/ks.cfg
  examples/k8s/static/virtualbox/machine.sh
  examples/k8s/static/virtualbox/poststepps.sh
  internal/helpers/check.go
  internal/operator/orbiter/kinds/clusters/kubernetes/adapt.go
  internal/operator/orbiter/kinds/clusters/kubernetes/ensure.go
  internal/operator/orbiter/kinds/clusters/kubernetes/join.go
  internal/operator/orbiter/kinds/clusters/kubernetes/query.go
  internal/operator/orbiter/kinds/clusters/kubernetes/scale.go
Labels: enhancement
