Repository caos/orbos, pull requests merged in 2021-08, with the labels that each got.

#799 fix(orbctl): add repokey parameter to configure command
  cmd/orbctl/configure.go
  pkg/git/client.go
  pkg/orb/orb.go
Labels: bug, enhancement

#800 fix(orbctl): correct unused variables for go vet
  internal/operator/orbiter/kinds/clusters/kubernetes/machines.go
Labels: bug

#693 chore: add logs secret script
  scripts/grafana-cloud-logs.yml.sh
  scripts/grafana-cloud-metrics.yml.sh
Labels: BOOM

#647 fix: update to golang 1.16.0 inclusive added arm build
  .github/workflows/dev-release.yml
  .github/workflows/release.yml
  .releaserc.js
  build/orbos/Dockerfile
  cmd/chore/gen-executables/main.go
  go.mod
Labels: enhancement, dependencies

#817 fix: enable more file descriptors for nginx
  internal/operator/nodeagent/dep/nginx/dep.go
  internal/operator/nodeagent/dep/systemd.go
Labels: bug, Node Agent

#828 fix: remove comment from line in systemd unit file
  internal/operator/nodeagent/dep/nginx/dep.go
  internal/operator/nodeagent/dep/nginx/dep_test.go
  internal/operator/orbiter/kinds/loadbalancers/dynamic/adapt.go
Labels: bug, Node Agent
